#include "AutoModePolicy.hpp"

#include <format>
#include <utility>

namespace core::agent {

std::string_view to_string(AutoExecutionPath path) noexcept {
  switch (path) {
  case AutoExecutionPath::Direct:
    return "direct";
  case AutoExecutionPath::Orchestrated:
    return "orchestrated";
  }
  return "direct";
}

AutoModePolicy::AutoModePolicy(
    core::llm::routing::AutoClassifier classifier) noexcept
    : classifier_(std::move(classifier)) {}

AutoModeDecision
AutoModePolicy::decide(std::string_view prompt,
                       AutoModeContext context) const noexcept {
  auto input = core::llm::routing::AutoClassifier::extract_signals(
      prompt, context.history_tokens, context.turn_count,
      context.has_tool_history);
  const auto classified = classifier_.classify(input);

  using core::llm::routing::TaskType;
  using core::llm::routing::Tier;

  const bool intrinsically_multi_step =
      classified.task_type == TaskType::Debugging ||
      classified.task_type == TaskType::Architecture ||
      classified.task_type == TaskType::Reasoning;
  const bool structurally_complex =
      classified.tier == Tier::Powerful || classified.complexity >= 0.58;
  const bool orchestrated = intrinsically_multi_step || structurally_complex;

  AutoModeDecision decision;
  decision.path = orchestrated ? AutoExecutionPath::Orchestrated
                               : AutoExecutionPath::Direct;
  decision.task_type = classified.task_type;
  decision.complexity = classified.complexity;
  decision.parallel_exploration = orchestrated &&
                                  classified.task_type != TaskType::Trivial &&
                                  classified.task_type != TaskType::Simple;
  // The condition is mutation, not the classifier's guess. A turn that stays
  // conversational pays no cost; any turn that actually writes must close
  // the evidence loop even when its original wording looked trivial.
  decision.verification_required_after_mutation = true;
  decision.reason = std::format(
      "{} path selected for {} work at {:.2f} complexity",
      to_string(decision.path),
      core::llm::routing::to_string(decision.task_type), decision.complexity);
  return decision;
}

std::string
AutoModePolicy::execution_contract(const AutoModeDecision &decision) const {
  std::string contract =
      std::format("\n\n[AUTO execution contract — generated by Filo]\n"
                  "Route: {}\n"
                  "Reason: {}\n",
                  to_string(decision.path), decision.reason);

  if (decision.path == AutoExecutionPath::Direct) {
    contract +=
        "Complete this request directly. Keep the workflow proportional; do "
        "not create "
        "ceremonial plans or delegate work that is cheaper to do here.\n";
  } else {
    contract += "Decompose before editing and keep the active plan visible "
                "through todos. "
                "Delegate bounded investigations to subagents instead of "
                "carrying all discovery "
                "in the parent context.\n";
    if (decision.parallel_exploration) {
      contract += "Issue independent read-only `task` calls together in one "
                  "model response so "
                  "Filo can execute them concurrently. Fan their concrete "
                  "findings back into one "
                  "writer; do not run concurrent mutating workers in the same "
                  "checkout.\n";
    }
  }

  contract += "Treat repository state and existing user changes as owned data: "
              "inspect before editing, "
              "preserve unrelated work, and review the final diff.\n";
  if (decision.verification_required_after_mutation) {
    contract += "After mutations, continue normal engineering work; Filo's "
                "completion hooks will run the repository quality gate. You "
                "may run targeted checks earlier for faster feedback, but do "
                "not duplicate the final gate ceremonially. If no configured "
                "or discovered check can genuinely run, state `Verification "
                "exception: <specific reason>` in the final answer.\n";
  }
  contract += "[/AUTO execution contract]";
  return contract;
}

} // namespace core::agent
